### ISSUE TITLE
How do I update latitude and longitude?

### ISSUE THREAD

**Issue by mohsen1** [hMatoba/piexifjs#1]

**Comment by hMatoba** [comment]
node example, north 37.429289 and west 122.138162.

    var piexif = require("piexifjs");
    var fs = require("fs");

    var filename1 = "in.jpg";
    var filename2 = "out.jpg";

    var jpeg = fs.readFileSync(filename1);
    var data = jpeg.toString("binary");

    var exifObj = piexif.load(data);
    exifObj["GPS"][piexif.GPSIFD.GPSLatitudeRef] = "N";
    exifObj["GPS"][piexif.GPSIFD.GPSLatitude] = [37429289, 1000000];
    exifObj["GPS"][piexif.GPSIFD.GPSLongitudeRef] = "W";
    exifObj["GPS"][piexif.GPSIFD.GPSLongitude] = [122138162, 1000000];
    var exifbytes = piexif.dump(exifObj);

    var newData = piexif.insert(exifbytes, data);
    var newJpeg = new Buffer(newData, "binary");
    fs.writeFileSync(filename2, newJpeg);

**Comment by mohsen1** [comment]
Thank you. My lat lang in in this format:

```
"latitude": 36.613230478624,
"longitude": -121.93234200195,
```

How can I use these numbers?

**Comment by hMatoba** [comment]
exifObj["GPS"][piexif.GPSIFD.GPSLatitudeRef] = "N";
exifObj["GPS"][piexif.GPSIFD.GPSLatitude] = [366132304, 10000000],
exifObj["GPS"][piexif.GPSIFD.GPSLongitudeRef] = "W";
exifObj["GPS"][piexif.GPSIFD.GPSLongitude] = [1219323420, 10000000];

**Comment by mohsen1** [comment]
Two questions:

* Where `N` and `W` values are coming from? Are they relative to lat-long numbers?
* Why did you put positive number for `GPSLongitude` while my longitude was negative?

**Comment by hMatoba** [comment]
latitude >= 0: North latitude -> "N"
latitude < 0: South latitude -> "S"
longitude >= 0: East longitude -> "E"
longitude < 0: West longitude -> "W"

**Comment by mohsen1** [comment]
Thank you!

**Comment by hMatoba** [comment]
Anytime.

**Comment by ipsips** [comment]
Hi, great library guys!

The above-suggested way of assigning latitude & longitude to an array of two – [numerator, denominator] – did not work for me. The resulting image was still not bearing any GPS info when i opened it with OS X Preview app.

What did work however was representing the coordinates as multidimensional array of deegrees, minutes and seconds like this:

```
var data = {
  lat: 59.43553989213321,
  lng: 24.73842144012451
}

exifObj["GPS"][piexif.GPSIFD.GPSLatitudeRef] = data.lat < 0 ? 'S' : 'N'
exifObj["GPS"][piexif.GPSIFD.GPSLatitude] = degToDmsRational(data.lat)
exifObj["GPS"][piexif.GPSIFD.GPSLongitudeRef] = data.lng < 0 ? 'W' : 'E'
exifObj["GPS"][piexif.GPSIFD.GPSLongitude] = degToDmsRational(data.lng)

/**
 * degToDmsRational(59.43553989213321) -> [[59, 1], [26, 1], [794, 100]]
 */

function degToDmsRational(degFloat) {
  var minFloat = degFloat % 1 * 60
  var secFloat = minFloat % 1 * 60
  var deg = Math.floor(degFloat)
  var min = Math.floor(minFloat)
  var sec = Math.round(secFloat * 100)

  return [[deg, 1], [min, 1], [sec, 100]]
}
```

**Comment by hMatoba** [comment]
Below code Works without problem for me on Chrome(Win, 54.0.2840.99 m (64-bit)).
Checked with: http://regex.info/exif.cgi

image:
![foo](https://cloud.githubusercontent.com/assets/4497270/20244882/e72cd5c2-a9d5-11e6-8bd5-1b431a7873e7.jpg)


        // make exif data
        var zerothIfd = {};
        var exifIfd = {};
        var gpsIfd = {};
        zerothIfd[piexif.ImageIFD.Make] = "Maker Name";
        zerothIfd[piexif.ImageIFD.XResolution] = [777, 1];
        zerothIfd[piexif.ImageIFD.YResolution] = [777, 1];
        zerothIfd[piexif.ImageIFD.Software] = "Piexifjs";
        exifIfd[piexif.ExifIFD.DateTimeOriginal] = "2010:10:10 10:10:10";
        exifIfd[piexif.ExifIFD.LensMake] = "Lens Maker";
        exifIfd[piexif.ExifIFD.Sharpness] = 777;
        exifIfd[piexif.ExifIFD.LensSpecification] = [[1, 1], [1, 1], [1, 1], [1, 1]];
        gpsIfd[piexif.GPSIFD.GPSVersionID] = [7, 7, 7, 7];
        gpsIfd[piexif.GPSIFD.GPSDateStamp] = "1999:99:99 99:99:99";
        gpsIfd[piexif.GPSIFD.GPSLatitudeRef] = "N";
        gpsIfd[piexif.GPSIFD.GPSLatitude] = [37429289, 1000000];
        gpsIfd[piexif.GPSIFD.GPSLongitudeRef] = "W";
        gpsIfd[piexif.GPSIFD.GPSLongitude] = [122138162, 1000000];
        var exifObj = {"0th":zerothIfd, "Exif":exifIfd, "GPS":gpsIfd};

        // get exif binary as "string" type
        var exifBytes = piexif.dump(exifObj);

**Comment by hMatoba** [comment]
Thank you. My way was wrong. Rational value as lat or lon has 3 length, not one length.

**Comment by kshipp** [comment]
I too had problems getting GPS to appear.  ipsips's solution works for showing the lat/lon, but I still cannot get any other GPS fields to display.  Any suggestions or sample code that actually works?
In photos, Altitude is an object of num & den.
I also can't get the GPSLongitudeRef and LatRef to display any values:
ie:  exifObj["GPS"][piexif.GPSIFD.GPSLongitudeRef] = "W";
Please provide a working example so we can get them to work.  Thanks.
