### ISSUE TITLE
IPTC

### ISSUE THREAD

**Issue by gavinvangent** [hMatoba/piexifjs#11]
Hi hMatoba,

Not sure if this is the right way to request a feature, so please let me know how to if not.

Will there be support for IPTC tags in the near future? I have spec to convert our perl runners to nodejs and this is the best nodejs exif read and write tool I've found yet. Only problem is the lack of IPTC support which means I can't migrate to nodejs soon.

Regards
gavinvangent

**Comment by hMatoba** [comment]
Just for exif. I won't add other specification support.
