### ISSUE TITLE
Can't write EXIF data if input data differs from expected value in TAGS array.

### ISSUE THREAD

**Issue by francois56234** [hMatoba/piexifjs#12]
I have an image with ProfileCopyright data ("aStringValue") set with a type of 'Ascii'.

I can read the image, get the EXIF, but when I write the EXIF to the modified file, the existing code retrieves the expected type for this field (TAGS[50942] -> "Byte") and attempt to save {50942, "Byte", "aStringValue"} which fails because "Byte" expects an Array, not a String.

I'm not familiar enough with EXIF to be sure whether the error lies in the input file or in piexeif (which is very nice, thank you). ProfileCopyright is not listed in the documentation for EXIF 2.3, but it is listed on http://www.exiv2.org/tags.html.

**Comment by hMatoba** [comment]
This library is based on official document. I'm not thinking to expand it for other document now.

**Comment by hMatoba** [comment]
If you want to set "Byte", convert string into array of integers(ex. "(30, 31, 50...)").
