### ISSUE TITLE
0th ImageDescription

### ISSUE THREAD

**Issue by lucastimmons** [hMatoba/piexifjs#16]
The loadsample.html example doesn't show ImageDescription (270) when the image loads. I can't find a way to extract it. 

Using the library I can write to 270 (zerothIfd[piexif.ImageIFD.ImageDescription] = "Description"; in the dumpsample.html file. 

Is there a reason ImageDescription doesn't appear?

**Comment by hMatoba** [comment]
?

https://github.com/hMatoba/MinifyJpegAsync/issues/4

**Comment by lucastimmons** [comment]
Same problem.

I want to resize an image but also keep the ImageDescritpion as part of the exif data. 

hMatoba/MinifyJpegAsync doesn't keep the ImageDescription data. So I was going to use piexifjs to copy the ImageDescription into memory, resize the image, then write the image description back to the resized image and download it.

In both projects the ImageDescription (Tag 270) isn't extracted from the image when the image is loaded in. In the example in hMatoba/MinifyJpegAsync the image description is gone when the image is downloaded. 

As you can see in these screen grabs, the photo itself has an image description but it doesn't appear when loaded into the PixelifJS LoadSample.html file.

<img width="396" alt="screen shot 2016-09-08 at 10 26 30 pm" src="https://cloud.githubusercontent.com/assets/1189974/18373584/603e2f16-7613-11e6-9778-267874e696e0.png">
<img width="709" alt="screen shot 2016-09-08 at 10 26 42 pm" src="https://cloud.githubusercontent.com/assets/1189974/18373585/603f1caa-7613-11e6-93cf-91aaea5d22cd.png">


This doesn't happen for every file. Sometimes the image description does show up. I just need to have a way to make sure it always shows up, even if it means no other metadata is saved.

**Comment by hMatoba** [comment]
Could yo give me images?

**Comment by lucastimmons** [comment]
Here are three I've tried and I get no image description but they do all have an image description. 

http://awesome.lucastimmons.com/testimages/1.jpg
http://awesome.lucastimmons.com/testimages/2.jpg
http://awesome.lucastimmons.com/testimages/3.jpg

**Comment by hMatoba** [comment]
<img width="396" alt="603e2f16-7613-11e6-9778-267874e696e0" src="https://cloud.githubusercontent.com/assets/4497270/18383903/a005101a-76c2-11e6-8231-48f7397da30c.png">

Is this really exif's ImageDescription? Isn't is XMP's?

**Comment by lucastimmons** [comment]
Here's one that came from the same source that does work in the LoadSample.html file.
http://awesome.lucastimmons.com/testimages/4.jpg

Looking at the raw data for both, the description is tagged like this: 

img2.jpg:

         <dc:description>
            <rdf:Alt>
               <rdf:li xml:lang="x-default">A gate blocks the entrance to Richard Henry Bain's fishing camp in La Conception, near Mont-Tremblant, Que. on Wednesday Sept. 5, 2012. Police sources confirmed they arrested a suspect by that name in the Montreal shooting that left one person dead and made headlines around the world. THE CANADIAN PRESS/Andy Blatchford</rdf:li>
            </rdf:Alt>
         </dc:description>

------------------
img4.jpg
         <dc:description>
            <rdf:Alt>
               <rdf:li xml:lang="x-default">Rogers Place Arena, the new home of the Edmonton Oilers, in Edmonton, Alta., on Thursday, September 8, 2016. THE CANADIAN PRESS/Jason Franson</rdf:li>
            </rdf:Alt>
         </dc:description>


So it appears they are tagged the same way. Not sure why one works and the other doesn't.

**Comment by hMatoba** [comment]
Isn't it XMP's!? Have you tried other library?
I tried and can't find "ImageDescription" it in exif.

http://regex.info/exif.cgi
