### ISSUE TITLE
Uncaught Given data is not jpeg

### ISSUE THREAD

**Issue by leknoppix** [hMatoba/piexifjs#17]
Hello

i will try to use the function remove, but i have an error when I choose a picture.
I use  like this:
`
var piexifjs = require('piexifjs');
piexifjs.remove(file);
`
Where file is mypicture: "C:\Users\leknoppix\Pictures\10 ans bac 2005\P1050914 - Copie.jpeg"

The console.log give this to return:
Given data is not jpeg.

I don't understand where is the problem. I think that is me but I don't look the solve.

**Comment by hMatoba** [comment]
Could you upload the jpeg?

**Comment by leknoppix** [comment]
![p1050914](https://cloud.githubusercontent.com/assets/708669/18556308/5d8a5fe4-7b6b-11e6-9e24-c29fc60c8106.JPG)

I use this but, I think that is not correct:
var jpeg = fs.readFileSync(file);
var data = jpeg.toString("binary");
piexifjs.remove(data);

**Comment by hMatoba** [comment]
It means solved?

**Comment by leknoppix** [comment]
Yes and No.
When I use a picture without EXIF, i obtin 
Uncaught Exif not found.

A idea?

**Comment by hMatoba** [comment]
No error ocured.

    var piexif = require("piexifjs");
    var fs = require("fs");
    
    var filename1 = "in.jpg";
    var filename2 = "out.jpg";
    
    var jpeg = fs.readFileSync(filename1);
    var data = jpeg.toString("binary");
    var new = piexif.remove(data);

**Comment by hMatoba** [comment]
use "try catch".

**Comment by leknoppix** [comment]
Thank

**Comment by lakuhana** [comment]
>This's the answer to the question : https://github.com/hMatoba/Piexif/issues/30#issuecomment-275818092 
Thumbnail information is wrong. If a jpeg has thumbnail, it must have 1st IFD and JPEGInterchangeFormatLength in Exif IFD(exif["Exif"][piexif.ExifIFD.JPEGInterchangeFormatLength]) value. JPEGInterchangeFormatLength means byte size of thumbnail.
Your image has thumbnail's information, but it shows thumbnail's size as byte is zero, so remove thumbnail's information.
```python
del exif["1st"]
del exif["thumbnail"]
piexif.dump(exif)
```
