### ISSUE TITLE
 exif.slice is not a function

### ISSUE THREAD

**Issue by shreejibawa** [hMatoba/piexifjs#18]
I am trying to add extracted exif object and its showing this error:

``` exif.slice is not a function```

````javascript
    that.insert = function (exif, jpeg) {
        var b64 = false;
        if (exif.slice(0, 6) != "\x45\x78\x69\x66\x00\x00") {
            throw ("Given data is not exif.");
        }
````

This is the basic exif object. Its same as when I got it. I have not modified it.:
```json
{
"0th"
"1st"
"Exif"
"GPS"
"Interop"
}
```

any idea why?

**Comment by hMatoba** [comment]
http://piexifjs.readthedocs.io/en/latest/functions.html#insert

**Comment by shreejibawa** [comment]
my bad. sorry.
