### ISSUE TITLE
Some exif data is corrupted after using insert()

### ISSUE THREAD

**Issue by acutexyz** [hMatoba/piexifjs#19]
Thanks for the work, 

I want to modify exif orientation, which I'm able to do for most images, but for some images some exif data (like "Make", "Model", "X-resolution", "Y-resolution") gets corrupted or lost.

So I tried to compare exif objects before and after modification on those problematic images, but when I try to get exif object using `load()` after inserting modified exif, I'm getting this error: 

`Uncaught 'unpack' error. Mismatch between symbol and string length. 2:0`.

_If I just take the inserted jpegData and create a blob out of it, some of exif data becomes corrupted:_

Before:

<img width="320" alt="screen shot 2017-02-22 at 4 35 25 pm" src="https://cloud.githubusercontent.com/assets/536944/23216032/32e7e538-f91d-11e6-926c-edfd99c61d96.png">

After:

<img width="322" alt="screen shot 2017-02-22 at 4 35 57 pm" src="https://cloud.githubusercontent.com/assets/536944/23216040/3b66e614-f91d-11e6-9f16-dee9f44f2abd.png">

Here is the code that I used:

```
function modifyOrientation(file) {

  var reader = new FileReader();

  reader.onload = function(e) {

    var origDataUrl = e.target.result;
    var exif = piexif.load(origDataUrl);
    console.log(exif);

    exif['0th'][piexif.ImageIFD.Orientation] = 1; // modifying orientation
    var dump = piexif.dump(exif);
    var inserted = piexif.insert(dump, origDataUrl);

    var modifiedExif = piexif.load(inserted); // <== error thrown here
    console.log(modifiedExif);

    debugger;
  };

  reader.readAsDataURL(file);
}
```

and here is the sample image:

![sample 2 - this night scene has sacrificed light for detail and contains no colour](https://cloud.githubusercontent.com/assets/536944/23215012/805a3644-f919-11e6-8f94-32732766268b.jpg)

**Comment by hMatoba** [comment]
Thank you. Fixed it.

**Comment by acutexyz** [comment]
Great, when are you going to publish 1.0.3 release?

**Comment by hMatoba** [comment]
Done : )
