### ISSUE TITLE
manipulating jpeg binary strings in windows

### ISSUE THREAD

**Issue by epikhighs** [hMatoba/piexifjs#2]
Hi @hMatoba ,

I'm considering using this tool to edit personal photos so I'm worried about data integrity.  In particular, I'm feeling hesitant/cautious on manipulating jpeg binary strings.  Forgive my ignorance, but is this safe to do?  And are there any edge cases or pitfalls I should be aware of?

Thanks!

**Comment by hMatoba** [comment]
'Makernote' of most(or some) makers' data of exif might be broken.
