### ISSUE TITLE
Question: Does .remove retain the color profile data

### ISSUE THREAD

**Issue by TheJaredWilcurt** [hMatoba/piexifjs#21]
I'm looking to convert JPG's to PNG's using ImageMagick's `convert.exe`. However, just running `convert.exe input.jpg output.png` will add additional EXIF metadata I don't want to the output. The `convert.exe` has an argument called `-strip` that removes the EXIF data, all comments, and all profiles. That includes removing the color profile data, and since I want the output to be lossless, I need to retain the color profile.

I'm looking into `piexifjs` as a pre-step, to remove the EXIF, then have `convert.exe` run to create the PNG.

The documentation for `.remove` doesn't go into detail as to what it removes and what it retains.

* http://piexifjs.readthedocs.io/en/latest/functions.html#remove

**Comment by hMatoba** [comment]
Removes only exif.

**Comment by TheJaredWilcurt** [comment]
Sweet, thanks
