### ISSUE TITLE
Massive memory usage when reading exif data

### ISSUE THREAD

**Issue by jczaplew** [hMatoba/piexifjs#22]
I am currently using `piexif` in an Ionic application for reading and writing exif data, and have noticed that when I call `piexif.load` on an image a disproportionate amount of memory is used. For example, reading the exif data on a 3mb image results in a peak memory usage of 300mb. When used on a larger image, such as a panorama, memory usage often exceeds 600mb and results in the app crashing. 

I'm not really sure where to start debugging this issue. It is possible that this is an edge case when `piexif` is used with Ionic, but I was consistently able to reproduce this behavior with a variety of images. Any thoughts or insights as to what in `piexif` would be resulting in this behavior?

Thanks for creating and sharing such a great library!

**Comment by hMatoba** [comment]
Node.js or browser?

**Comment by jczaplew** [comment]
Browser. It is running in a webview as a native app on iOS

**Comment by hMatoba** [comment]
The problem could be resolved by below merge.
https://github.com/hMatoba/piexifjs/pull/23

**Comment by jczaplew** [comment]
Great! I'll have a look.
