### ISSUE TITLE
How to set GPSLatitude and GPSLongitude?

### ISSUE THREAD

**Issue by untitledlt** [hMatoba/piexifjs#24]
What GPS coordinates format does it accept?
Don't see anything in docs, tried to guess but no success.

**Comment by untitledlt** [comment]
i found an answer here: https://github.com/hMatoba/piexifjs/issues/1

**Comment by hMatoba** [comment]
Thank you for informing here. I feel that there is a need to add sample.

**Comment by hMatoba** [comment]
Resolved.
https://github.com/hMatoba/piexifjs/commit/eb3c91e0ad2ecb103ffbda789f827382bb816007
