### ISSUE TITLE
only load, dump, insert, but exif change

### ISSUE THREAD

**Issue by GHolk** [hMatoba/piexifjs#26]
I just load, then dump, insert, no change exif.
and the output image of insert can not be read by
`exif_read_data()` in PHP.

any suggestion?

**Comment by hMatoba** [comment]
More information. Enviroment, code, output...

**Comment by GHolk** [comment]
sorry i can't.
i dont know exif structure, nether read binary.

the image's exif output cannot be read by `exif_read_data()` in php, 
and my android phone.

but still some program can read it, 
like `identify` of **image magick** , **jhead**.

there is two before and after only load, dump, insert,
but their size different.

 -  [well image](http://140.116.80.138/~2017GO/test/well_img.jpg)
 -  [changed image](http://140.116.80.138/~2017GO/test/change_img.jpg)

**Comment by hMatoba** [comment]
Which environment? Server, PC browser or SP browser? Chrome, Firefox?

**Comment by GHolk** [comment]
php server is linux,
client test on chroiume, firefox, node.

**Comment by hMatoba** [comment]
I checked images by "http://exif.regex.info/exif.cgi(using Image::ExifTool)". It shows exif without alerts.

I don't use php and android, so I can't get details.

**Comment by hMatoba** [comment]
No code, so I can do nothing.
