### ISSUE TITLE
PNG support?

### ISSUE THREAD

**Issue by alifeinbinary** [hMatoba/piexifjs#28]
What's the likelihood that piexifjs could support png? Any plans for implementing this in the future? Thanks for all the hard work, it's a really great library :)

**Comment by hMatoba** [comment]
No.
PNG images don't have exif.

**Comment by humorHan** [comment]
@hMatoba Because PNG doesn't have exif, is there any other solution?

**Comment by hkung77** [comment]
Perhaps this can be revisited since it seems like there is EXIF chunk on Png files

https://stackoverflow.com/questions/9542359/does-png-contain-exif-data-like-jpg

**Comment by leiming** [comment]
@hMatoba , could  you reopen is issue due to https://stackoverflow.com/questions/9542359/does-png-contain-exif-data-like-jpg ?

**Comment by asc0910** [comment]
As this repository is not supported anymore, I added png and webp support to this fork.
https://github.com/asc0910/exif-library
