### ISSUE TITLE
Parse exif data to string.

### ISSUE THREAD

**Issue by zafarsultandias** [hMatoba/piexifjs#31]
I am using your library for the first time. When I read the data, I get something like:

{
    "Exif": {
        "ExposureTime": [1, 800],
        "FNumber": [71, 10]
    }
}

My question is, how can we get the values "ExposureTime" & "FNumber" as strings? Also, there are other objects like "GPSLatitude": [ [Object], [Object], [Object] ]

Why these values are not in string, Is there any method to get them as string?

**Comment by hMatoba** [comment]
http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf
