### ISSUE TITLE
Release 1.0.4 is not available on npm

### ISSUE THREAD

**Issue by sachingarg05** [hMatoba/piexifjs#34]
npm still reports and installs 1.0.3 as latest release.

**Comment by arj03** [comment]
bump

**Comment by hMatoba** [comment]
Sorry for sorry for inconvenience. Within one week.

**Comment by arj03** [comment]
Thanks!

**Comment by hMatoba** [comment]
Published.

**Comment by hMatoba** [comment]
Thank you for letting me know!
