### ISSUE TITLE
jpeg.slice is not a function - I got this error

### ISSUE THREAD

**Issue by gabibraharu** [hMatoba/piexifjs#35]
Hello,

I used this code for modify exif and I got the error "jpeg.slice is not a function" when 
var exifModified = piexif.insert(exifBytes, canvas);
Uncaught (in promise) TypeError: jpeg.slice is not a function
    at Object.that.insert (piexif.js:61)
    at html2canvas.then.canvas (indexh.php:57)
    at <anonymous>

Below is my code:

 function exportPicture() 
            {
                  var ld=document.getElementsByClassName("gascuns");
                  ld.className="garatat";
                  var ndom=document.getElementsByClassName("aratat");
                  var el = document.getElementById(ndom[0].id);
                  html2canvas(document.querySelector('#'+ndom[0].id)).then(canvas => {
                  var a = document.createElement('a');
                  a.href = canvas.toDataURL("image/jpg").replace("image/jpg", "image/octet-stream");
                  var zerothIfd = {};
                  var exifIfd = {};
                  var gpsIfd = {};
                  zerothIfd[piexif.ImageIFD.Make] = "Maker Name";
                  zerothIfd[piexif.ImageIFD.XResolution] = [300, 1];
                  zerothIfd[piexif.ImageIFD.YResolution] = [300, 1];
                  zerothIfd[piexif.ImageIFD.Software] = "Piexifjs";
                  exifIfd[piexif.ExifIFD.DateTimeOriginal] = "2018:10:10 10:10:10";
                  exifIfd[piexif.ExifIFD.LensMake] = "Lens Maker";
                  exifIfd[piexif.ExifIFD.Sharpness] = 777;
                  exifIfd[piexif.ExifIFD.LensSpecification] = [[1, 1], [1, 1], [1, 1], [1, 1]];
                  gpsIfd[piexif.GPSIFD.GPSVersionID] = [7, 7, 7, 7];
                  gpsIfd[piexif.GPSIFD.GPSDateStamp] = "2018:99:99 99:99:99";
                  var exifObj = {"0th":zerothIfd, "Exif":exifIfd, "GPS":gpsIfd};
                  var exifBytes = piexif.dump(exifObj);
                  var exifModified = piexif.insert(exifBytes, canvas); //here I got the error jpeg.slice is not a function
                  base_image = new Image();
                  base_image.src = a.href;
                  base_image.onload = function(){
                      context = canvas.getContext('2d');
                      context.drawImage(base_image, 0,0);
                      saveCanvas(canvas);
                   };
                });
                ld.className="gascuns";
              } 
           
          function saveCanvas(x_canvas){x_canvas.toBlob(function(blob) {saveAs(blob, "screenshot.JPG");},"image/jpeg");}

**Comment by hMatoba** [comment]
try `canvas.toDataURL("image/jpeg")` not `canvas.toDataURL("image/jpg")`.
