### ISSUE TITLE
'pack' error. Got invalid type argument

### ISSUE THREAD

**Issue by pranksinatra** [hMatoba/piexifjs#43]
Hi, we're using Piexifjs in production at [BeFunky](https://www.befunky.com/) (an online photo editor) and have been getting this error pretty often:
`'pack' error. Got invalid type argument`

I looked over the call sites of the `pack()` function, and my best guess is that the culprit is line 457, where `_dict_to_bytes()` converts `raw_value` to an array if its a number, but not if its any other type (string, undefined, null, etc).

I'll let you know if I'm able to get an actual stack trace, but I just wanted to pass this along in case it was an oversight. Thanks for this super handy library.

**Comment by tomscript** [comment]
Seeing this by way of `https://www.npmjs.com/package/jpeg-autorotate`. Friendly ping

**Comment by hMatoba** [comment]
Thank you for letting me know. 
In version 2.0, I add some type checks. It's will resolve this issue.

Could you re-open this issue, when you got the image that throw this error?

**Comment by pranksinatra** [comment]
@hMatoba , glad to hear you're working on a 2.0.

In the meantime, I discovered that the reason there's no stack trace is that you're throwing a string instead of an Error object, e.g.

Missing stack trace:
```js
throw "'pack' error"
```

Has stack trace:
```js
throw new Error("'pack' error")
```

If you'd like, I can submit a PR. Just let me know

**Comment by hMatoba** [comment]
Could you send me PR?

**Comment by pranksinatra** [comment]
Sure, just submitted one.
