### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for '0th' in data:image...

### ISSUE THREAD

**Issue by Arxcis** [hMatoba/piexifjs#56]
**Code failing**
```
let exifBytes = piexifjs.dump(dataURL);
```
**Error message**
>TypeError: Cannot use 'in' operator to search for '0th' in data:image...

**Environment**
Chrome 70
Vue 3.1.0
cmd `vue-cli-service serve --watch`
"piexifjs": "^1.0.4",

**MDN Related error**
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/in_operator_no_object

Nobody else get this error?
Fixed in piexif 2.0 ?
Scanning through the source codes I can see that the `in` operator is used everywhere.

**Comment by hMatoba** [comment]
https://github.com/hMatoba/piexifjs#how-to-use

**Comment by Arxcis** [comment]
Ah of course! Thank you very much :+1: 

**Solution**
DON'T pass `dataurl` as agrument to `piexifjs.dump`. It takes an `exifojb` as argument, which is returned from the `piexifjs.load`.

**Correct usage**
```
let exifojb = piexifjs.load(dataurl);
let exifstr = piexifjs.dump(exifobj);
```
