### ISSUE TITLE
Problem when running inside cordova

### ISSUE THREAD

**Issue by HarelM** [hMatoba/piexifjs#60]
I have no clue why, but the following image does not get any exif info when used inside cordova.
When using the same code on desktop browser the data is fetched correctly.
![img_20190205_233435](https://user-images.githubusercontent.com/3269297/52352899-280c3500-2a36-11e9-9f49-50b0eea7e2cb.jpg)
How can I debug this?

**Comment by HarelM** [comment]
Seems like this was not related to this library after all... Closing.

**Comment by josephlaw** [comment]
@HarelM can you share how to fix your problem? because i also using cordova.

**Comment by HarelM** [comment]
The problem was a bug in a cordova plugin where the exif information was lost when using the gallery.
The following line solved it:
https://github.com/IsraelHikingMap/Site/blob/e38e4b47d333bb86168e02b2731d4b10556a6b43/IsraelHiking.Web/sources/application/directives/image-capture.directive.ts#L65
Relevant issues:
https://github.com/IsraelHikingMap/Site/issues/932
https://github.com/apache/cordova-plugin-camera/issues/329
