### ISSUE TITLE
Problem when reading or writing in Chinese

### ISSUE THREAD

**Issue by codeloft** [hMatoba/piexifjs#63]
Hello, gays I love  this library,it works well;
but i met some problems, it can not read or write in Chines;
For example:
I wrote "这里是中文" in "ImageIFD.Make",but i got an error info "è¿éæ¯ä¸­æ"
so how can i solve this problem;
thank you again;
![image](https://user-images.githubusercontent.com/31199696/55770690-d58fd900-5ab7-11e9-82d8-f54242b3b828.png)

**Comment by hMatoba** [comment]
Check type for "Make". It is ascii.
https://www.exif.org/Exif2-2.PDF
