### ISSUE TITLE
bower

### ISSUE THREAD

**Issue by danialfarid** [hMatoba/piexifjs#7]
This is awesome library.
Could you push it to bower?

**Comment by hMatoba** [comment]
I would do it on this weekend.
Wait for a while. I'll inform here.

**Comment by hMatoba** [comment]
Done : )
http://bower.io/search/?q=piexifjs

**Comment by danialfarid** [comment]
Thanks, I ended up using custom scripts, but this plugin looks solid I might come back to add this as dependency if more features for exif is needed for ng-file-upload plugin.
